# Generated by Django 5.2.14 on 2026-05-28 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("results", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TypingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "keystroke_log",
                    models.JSONField(default=list, help_text="Detailed keystroke timing log"),
                ),
                (
                    "error_positions",
                    models.JSONField(default=list, help_text="Positions where errors occurred"),
                ),
                (
                    "timing_data",
                    models.JSONField(
                        default=dict, help_text="Timing analysis: avg_delay, p95_delay, etc."
                    ),
                ),
                (
                    "burst_speed_max",
                    models.FloatField(
                        default=0.0, help_text="Maximum burst WPM (peak speed over 2-second window)"
                    ),
                ),
                ("burst_speed_avg", models.FloatField(default=0.0, help_text="Average burst WPM")),
                (
                    "finger_speeds",
                    models.JSONField(blank=True, default=dict, help_text="Speed per finger/hand"),
                ),
                (
                    "result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="results.result",
                    ),
                ),
            ],
            options={
                "verbose_name": "Typing Session",
                "verbose_name_plural": "Typing Sessions",
                "db_table": "typing_sessions",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_tests", models.PositiveIntegerField(default=0)),
                ("total_time_seconds", models.PositiveIntegerField(default=0)),
                ("avg_wpm", models.FloatField(default=0.0)),
                ("best_wpm", models.FloatField(default=0.0)),
                ("avg_accuracy", models.FloatField(default=0.0)),
                ("avg_consistency", models.FloatField(default=0.0)),
                ("avg_raw_wpm", models.FloatField(default=0.0)),
                (
                    "weak_keys",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Keys with highest error rates: {key: error_count}",
                    ),
                ),
                (
                    "wpm_distribution",
                    models.JSONField(
                        blank=True, default=list, help_text="WPM values for distribution chart"
                    ),
                ),
                (
                    "accuracy_distribution",
                    models.JSONField(
                        blank=True, default=list, help_text="Accuracy values for distribution chart"
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional computed metrics"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Snapshot",
                "verbose_name_plural": "Analytics Snapshots",
                "db_table": "analytics_snapshots",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["user", "period_type", "-period_start"],
                        name="analytics_s_user_id_7eb92f_idx",
                    )
                ],
                "unique_together": {("user", "period_type", "period_start")},
            },
        ),
    ]
