# Generated by Django 5.2.14 on 2026-05-28 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="ISO language code (e.g., 'en', 'es', 'fr')",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("flag_emoji", models.CharField(blank=True, default="", max_length=10)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "languages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("source", models.CharField(blank=True, default="", max_length=200)),
                ("author", models.CharField(blank=True, default="", max_length=100)),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("char_count", models.PositiveIntegerField(default=0)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("short", "Short (< 50 words)"),
                            ("medium", "Medium (50–100 words)"),
                            ("long", "Long (100+ words)"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="wordlists.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
                "db_table": "quotes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WordList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("words", models.JSONField(default=list, help_text="JSON array of words")),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of words in the list (auto-calculated)"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is a built-in default word list"
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="word_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_lists",
                        to="wordlists.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word List",
                "verbose_name_plural": "Word Lists",
                "db_table": "word_lists",
                "ordering": ["-is_default", "name"],
                "indexes": [
                    models.Index(
                        fields=["language", "difficulty"], name="word_lists_languag_f2d8d6_idx"
                    ),
                    models.Index(
                        fields=["is_public", "is_default"], name="word_lists_is_publ_55415b_idx"
                    ),
                ],
            },
        ),
    ]
