# Generated by Django 5.2.14 on 2026-05-28 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board_type",
                    models.CharField(
                        choices=[
                            ("global", "All Time"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("mode", models.CharField(default="time", max_length=20)),
                ("duration", models.PositiveIntegerField(default=60)),
                ("best_wpm", models.FloatField(default=0.0)),
                ("avg_wpm", models.FloatField(default=0.0)),
                ("best_accuracy", models.FloatField(default=0.0)),
                ("total_tests", models.PositiveIntegerField(default=0)),
                ("rank", models.PositiveIntegerField(default=0)),
                ("period_start", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leaderboard Entry",
                "verbose_name_plural": "Leaderboard Entries",
                "db_table": "leaderboard_entries",
                "ordering": ["-best_wpm"],
                "indexes": [
                    models.Index(
                        fields=["board_type", "mode", "duration", "-best_wpm"],
                        name="leaderboard_board_t_78b027_idx",
                    ),
                    models.Index(
                        fields=["board_type", "-best_wpm"], name="leaderboard_board_t_ef1e84_idx"
                    ),
                ],
                "unique_together": {("user", "board_type", "mode", "duration", "period_start")},
            },
        ),
    ]
