"""
Analytics — Models
===================
"""

from django.conf import settings
from django.db import models

from apps.core.models import TimeStampedModel


class AnalyticsSnapshot(TimeStampedModel):
    """
    Aggregated analytics snapshots for a user over a time period.
    Generated by Celery background tasks.
    """

    class PeriodType(models.TextChoices):
        DAILY = "daily", "Daily"
        WEEKLY = "weekly", "Weekly"
        MONTHLY = "monthly", "Monthly"

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="analytics_snapshots",
    )

    period_type = models.CharField(max_length=10, choices=PeriodType.choices)
    period_start = models.DateField()
    period_end = models.DateField()

    # Aggregated Metrics
    total_tests = models.PositiveIntegerField(default=0)
    total_time_seconds = models.PositiveIntegerField(default=0)
    avg_wpm = models.FloatField(default=0.0)
    best_wpm = models.FloatField(default=0.0)
    avg_accuracy = models.FloatField(default=0.0)
    avg_consistency = models.FloatField(default=0.0)
    avg_raw_wpm = models.FloatField(default=0.0)

    # Detailed Metrics (JSON)
    weak_keys = models.JSONField(
        default=dict,
        blank=True,
        help_text="Keys with highest error rates: {key: error_count}",
    )
    wpm_distribution = models.JSONField(
        default=list,
        blank=True,
        help_text="WPM values for distribution chart",
    )
    accuracy_distribution = models.JSONField(
        default=list,
        blank=True,
        help_text="Accuracy values for distribution chart",
    )
    metrics = models.JSONField(
        default=dict,
        blank=True,
        help_text="Additional computed metrics",
    )

    class Meta:
        db_table = "analytics_snapshots"
        verbose_name = "Analytics Snapshot"
        verbose_name_plural = "Analytics Snapshots"
        ordering = ["-period_start"]
        unique_together = ("user", "period_type", "period_start")
        indexes = [
            models.Index(fields=["user", "period_type", "-period_start"]),
        ]

    def __str__(self):
        return f"{self.user.username} — {self.period_type} ({self.period_start})"


class TypingSession(TimeStampedModel):
    """
    Detailed typing session data for deep analytics.
    Stores granular keystroke analysis.
    """

    result = models.OneToOneField(
        "results.Result",
        on_delete=models.CASCADE,
        related_name="session",
    )

    # Keystroke Analysis
    keystroke_log = models.JSONField(
        default=list,
        help_text="Detailed keystroke timing log",
    )
    error_positions = models.JSONField(
        default=list,
        help_text="Positions where errors occurred",
    )
    timing_data = models.JSONField(
        default=dict,
        help_text="Timing analysis: avg_delay, p95_delay, etc.",
    )

    # Burst Analysis
    burst_speed_max = models.FloatField(
        default=0.0,
        help_text="Maximum burst WPM (peak speed over 2-second window)",
    )
    burst_speed_avg = models.FloatField(
        default=0.0,
        help_text="Average burst WPM",
    )

    # Finger Analysis
    finger_speeds = models.JSONField(
        default=dict,
        blank=True,
        help_text="Speed per finger/hand",
    )

    class Meta:
        db_table = "typing_sessions"
        verbose_name = "Typing Session"
        verbose_name_plural = "Typing Sessions"

    def __str__(self):
        return f"Session for Result #{self.result_id}"
